routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('students', 'StudentsController');
Route::resource('financial', 'FinancialsController');
Route::resource('documents', 'DocumentsController');
Route::resource('dashboard', 'DashboardController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('register', function(){
  //  return '<h1>Acesso restrito! </h1>';
//});

resources/views/dashboard.blade.php
@extends('templates/base')

@include('components/navbar')
@include('components/sidebar')

@section('container')
  <div class="content right" id="blacklistPage">
    <div class="fix-space">
      
      <div class="main-list">
        <div class="list-item-header">
          <span class="col">Cliente</span>
          <span class="col">Livro</span>
          <span class="col">Entrega</span>
        </div>

        
        
      </div>

    </div>
  </div>
@endsection

resources/views/documents.blade.php
@extends('templates/base')

@include('components/navbar')
@include('components/sidebar')

@section('container')
  <div class="content right" id="blacklistPage">
    <div class="fix-space">
      
      <div class="main-list">
        <div class="list-item-header">
          <span class="col">Cliente</span>
          <span class="col">Livro</span>
          <span class="col">Entrega</span>
        </div>

      </div>

    </div>
  </div>
@endsection

resources/views/financials.blade.php
@extends('templates/base')

@include('components/navbar')
@include('components/sidebar')

@section('container')
  <div class="content right" id="blacklistPage">
    <div class="fix-space">
      
      <div class="main-list">
        <div class="list-item-header">
          <span class="col">Cliente</span>
          <span class="col">Livro</span>
          <span class="col">Entrega</span>
        </div>

      </div>

    </div>
  </div>
@endsection

resources/views/home.blade.php
@extends('../templates/base')

@section('container')

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Formatura 2019</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#formanos">Formandos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Financeiro</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#comissao">Comissão</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contato">Contato</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">LOGIN</a>
            </li>
            <li class="nav-item">
              <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="menu__item" id="logoutButton">Sair</a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
              </form>
            </li>  
          </ul>
        </div>
      </div>
    </nav>


    <!-- Header -->
    <header class="masthead">
      <div class="container">
        <div class="intro-text">
          <div class="intro-lead-in">Comissão de Formatura FATEC</div>
          <div class="intro-heading text-uppercase">#FORMOU</div>
          <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#services">Tell Me More</a>
        </div>
      </div>
    </header>

    <!-- Services -->
    <section id="formandos">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Formandos</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
          </div>
        </div>
        <div class="row text-center">
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">E-Commerce</h4>
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
          </div>
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">Responsive Design</h4>
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
          </div>
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">Web Security</h4>
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
          </div>
        </div>
      </div>
    </section>
    <!-- Team -->
    <section class="bg-light" id="comissao">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">A Comissão</h2>
            <h3 class="section-subheading text-muted">Time da Comissão de Formatura</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/1.jpg" alt="">
              <h4>Kay Garland</h4>
              <p class="text-muted">Lead Designer</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/2.jpg" alt="">
              <h4>Larry Parker</h4>
              <p class="text-muted">Lead Marketer</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/3.jpg" alt="">
              <h4>Diana Pertersen</h4>
              <p class="text-muted">Lead Developer</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/1.jpg" alt="">
              <h4>Kay Garland</h4>
              <p class="text-muted">Lead Designer</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/2.jpg" alt="">
              <h4>Larry Parker</h4>
              <p class="text-muted">Lead Marketer</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/3.jpg" alt="">
              <h4>Diana Pertersen</h4>
              <p class="text-muted">Lead Developer</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/1.jpg" alt="">
              <h4>Kay Garland</h4>
              <p class="text-muted">Lead Designer</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/2.jpg" alt="">
              <h4>Larry Parker</h4>
              <p class="text-muted">Lead Marketer</p>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/3.jpg" alt="">
              <h4>Diana Pertersen</h4>
              <p class="text-muted">Lead Developer</p>
            </div>
          </div>
        </div>        

        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <p class="large text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>
          </div>
        </div>
      </div>
    </section>
    <!-- Contact -->
    <section id="contato">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Fale Conosco</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <form id="contactForm" name="sentMessage" novalidate>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input class="form-control" id="name" type="text" placeholder="Your Name *" required data-validation-required-message="Please enter your name.">
                    <p class="help-block text-danger"></p>
                  </div>
                  <div class="form-group">
                    <input class="form-control" id="email" type="email" placeholder="Your Email *" required data-validation-required-message="Please enter your email address.">
                    <p class="help-block text-danger"></p>
                  </div>
                  <div class="form-group">
                    <input class="form-control" id="phone" type="tel" placeholder="Your Phone *" required data-validation-required-message="Please enter your phone number.">
                    <p class="help-block text-danger"></p>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <textarea class="form-control" id="message" placeholder="Your Message *" required data-validation-required-message="Please enter a message."></textarea>
                    <p class="help-block text-danger"></p>
                  </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-12 text-center">
                  <div id="success"></div>
                  <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Send Message</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Your Website 2018</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

@endsection

resources/views/students-form.blade.php
@extends('templates/base')

@include('components/navbar')
@include('components/sidebar')

@section('container')
  <div class="content right" id="autorPage">
    <div class="fix-space">

      @if ($action == 1)
          <form class="form" action="{{ route('students.store') }}" method="post">
      @else
          <form class="form" action="{{ route('students.update', $reg->id) }}" method="post">
          {!! method_field('put') !!}
      @endif      
        {{ csrf_field() }}
        
        <div class="line">
          <label class="lbl" for="nome">Nome:</label>
          <input type="text" class="ipt-text" id="nome" name="nome" value="{{ $reg->nome or old('nome') }}">
        </div>
        <div class="line">
          <label class="lbl" for="email">E-mail:</label>
          <input type="text" class="ipt-text" id="email" name="email" value="{{ $reg->email or old('email') }}">
        </div>
        <div class="line">
          <label class="lbl" for="endereco">Endereço:</label>
          <input type="text" class="ipt-text" id="endereco" name="endereco" value="{{ $reg->endereco or old('endereco') }}">
        </div>
        <div class="line">
          <label class="lbl" for="cep">CEP:</label>
          <input type="text" class="ipt-text" id="cep" name="cep" value="{{ $reg->cep or old('cep') }}">
        </div>
        <div class="line">
          <label class="lbl" for="telefone1">Telefone 1:</label>
          <input type="text" class="ipt-text" id="telefone1" name="telefone1" value="{{ $reg->telefone1 or old('telefone1') }}">
        </div>
        <div class="line">
          <label class="lbl" for="telefone2">Telefone 2:</label>
          <input type="text" class="ipt-text" id="telefone2" name="telefone2" value="{{ $reg->telefone2 or old('telefone2') }}">
        </div>
        <div class="line">
          <label class="lbl" for="rf">RG:</label>
          <input type="text" class="ipt-text" id="rg" name="rg" value="{{ $reg->rg or old('rg') }}">
        </div>
        <div class="line">
          <label class="lbl" for="cpf">CPF:</label>
          <input type="text" class="ipt-text" id="cpf" name="cpf" value="{{ $reg->cpf or old('cpf') }}">
        </div>

        <div class="line">
          <label class="lbl" for="idCurso" id="curso">Curso</label>
          <select class="ipt-text select" id="idCurso" name="idCurso">
            <option value="0">Selecione</option>
            @foreach ($courses as $c)
              <option value="{{ $c->id }}" @if ((isset ($reg) and $c->id == $reg->idCurso) or old('idCurso') == $c->id) selected @endif>{{ $c->nome }}</option>
            @endforeach
          </select>
        </div>

        <div class="line">
          <label class="lbl" for="idTurno" id="turno">Turno</label>
          <select class="ipt-text select" id="idTurno" name="idTurno">
            <option value="0">Selecione</option>
            @foreach ($shifts as $t)
              <option value="{{ $t->id }}" @if ((isset ($reg) and $t->id == $reg->idTurno) or old('idTurno') == $t->id) selected @endif>{{ $t->nome }}</option>
            @endforeach
          </select>
        </div>

        <div class="line">
          <label class="lbl" for="comissao">Comissão:</label>
          <input type="radio" class="ipt-text" id="comissao" name="comissao" value="{{ $reg->turno or old('turno') }}">
        </div>

        <div class="buttons-list">
          @if ($action == 2)
            <form style="display: inline-block;" method="POST" action="{{ route('students.destroy', $reg->id) }}">
              {{ method_field('DELETE') }}
              {{ csrf_field() }}

              <button type="submit" class="buttons-list__item remove">Remover</button>
            </form>
          @endif
          <a href="/books" class="buttons-list__item" id="cancelar">Cancelar</a><!--
          --><input type="submit" class="buttons-list__item" value="Salvar" id="salvar">
        </div>
      </form>

    </div>
  </div>
@endsection

resources/views/students-list.blade.php
@extends('templates/base')

@include('components/navbar')
@include('components/sidebar')

@section('container')

  <div class="content right" id="autorPage">
    <div class="fix-space">

      <div class="main-list">
        <div class="list-item-header">
          <span class="col">Nome</span>
          <span class="col">Curso</span>
          <span class="col">Turno</span>
          <span class="col"></span>
        </div>

        @foreach ($students as $student)
          <a href="students/{{ $student->id }}" class="list-item">
            <span class="col">{{ $student->nome }}</span>
            <span class="col">{{ $student->curso }}</span>
            <span class="col">{{ $student->turno }}</span>
            <span class="col"></span>
          </a>
        @endforeach        
      </div>

      <div class="buttons-list">
        <a href="/registration" class="buttons-list__item" id="voltar">Voltar</a>
        <a href="{{ route('students.create') }}" class="buttons-list__item" id="novo">Novo</a>
      </div>
    </div>
  </div>

@endsection